pool:
  vmImage: 'ubuntu-16.04' # Hosted Ubuntu 1604
  demands: maven


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'app/pom.xml'
    goals: 'compile package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    codeCoverageToolOption: 'Cobertura'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'